- name: Install nginx site for letsencrypt requests
  template:
    src: node-exporter-nginx.j2
    dest: /etc/nginx/applications/node_exporter.conf

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false