---
- name: Wait for system ready
  hosts: '{{ target }}'
  gather_facts: false
  become: true
  tasks:
    - name: check archive node flag
      fail:
        msg: 'you need to set the archive_node flag as true'
      when: archive_node is not defined

    - name: Wait for nodes to become reachable
      wait_for_connection:

    - name: Update and upgrade the machine
      apt:
        upgrade: dist
        update_cache: true

- name: Validator Archive Node Setup
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  roles:
    - validator_polkadot_prepare
    - process_exporter
    - node_exporter
    - promtail
    - validator_polkadot_update
