---
- name: backup keystore
  copy:
    src: "{{ chain_path | default('/home/polkadot/.local/share/polkadot')  }}/chains/{{ polkadot_network_id }}/keystore"
    dest: '/home/polkadot/keystore'
    remote_src: yes
