---
- name: install packages
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open ssh port
  command: ufw allow ssh
  # when:
    # - not ufw_status_result.stdout is search(ssh_port ~ "/tcp.*ALLOW IN.*Anywhere")
    
- name: open https port
  command: ufw allow https
  # when:
    # - not ufw_status_result.stdout is search(https_port ~ "/tcp.*ALLOW IN.*Anywhere")

- name: open http port
  command: ufw allow http

- name: open p2p port
  command: ufw allow {{ p2p_port }}/tcp
  when:
    - not ufw_status_result.stdout is search(p2p_port ~ "/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")
