---
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    groups: ['polkadot']
    append: yes
    shell: /bin/bash

- name: set folder permission if there is an alternative base_path for polkadot
  file:
    path: '{{ chain_path }}'
    state: directory
    owner: polkadot
    group: polkadot
    recurse: true
    mode: 0755
  when: chain_path is defined
  changed_when: false
